const product2 = {
  earbud: [
    {
      id: crypto.randomUUID(),
      title:
        "boAt Airdopes 141 Bluetooth Truly Wireless in Ear Earbuds with 42H Playtime, Beast Mode(Low Latency Upto 80ms) for Gaming, IPX4 Water Resistance, ENx Tech, IWP, Smooth Touch Controls(Cyan Cider)",
      img: "https://m.media-amazon.com/images/I/31BMd11KciL._SY300_SX300_.jpg",
      img2: "https://m.media-amazon.com/images/I/51IIMMnQ7cL._SY450_.jpg",
      img3: "https://m.media-amazon.com/images/I/81NXl8ObnEL._SY450_.jpg",
      img4: "https://m.media-amazon.com/images/I/71Dbhs4BLZL._SY450_.jpg",
      img5: "https://m.media-amazon.com/images/I/71DxKhGrLuL._SY450_.jpg",
      price: 4490,
      discount: 78,
      qty: 1,
      category: "earbud",
    },
    {
      id: crypto.randomUUID(),
      title:
        "CrossBeats Newly launched Revolt Hybrid Active Noise Cancelling Wireless Bluetooth Earbuds, 48hrs Playtime TWS, 10 mm Ti-Alloy Driver, EchoBlast™, 40ms Low Latency Earphone-Black",
      img: "https://m.media-amazon.com/images/I/61J9BzebDnL._SY450_.jpg",
      img2: "https://m.media-amazon.com/images/I/61f1IQifWXL._SY450_.jpg",
      img3: "https://m.media-amazon.com/images/I/61axYGTUdVL._SY450_.jpg",
      img4: "https://m.media-amazon.com/images/I/81o04TvhnIL._SY450_.jpg",
      img5: "https://m.media-amazon.com/images/I/61t9SMyZ9aL._SY450_.jpg",
      price: 9999,
      discount: 75,
      qty: 1,
      category: "earbud",
    },
    {
      id: crypto.randomUUID(),
      title:
        "OnePlus Nord Buds True Wireless in Ear Earbuds with Mic, 12.4mm Titanium Drivers, Playback:Up to 30hr case, 4-Mic Design + AI Noise Cancellation, IP55 Rating, Fast Charging (Black Slate)",
      img: "https://m.media-amazon.com/images/I/51ws0E8cnbL._SL1500_.jpg",
      img2: "https://m.media-amazon.com/images/I/51ws0E8cnbL._SL1500_.jpg",
      img3: "https://m.media-amazon.com/images/I/51gX3E0vzjL._SL1500_.jpg",
      img4: "https://m.media-amazon.com/images/I/41-vUVwh5VL._SL1500_.jpg",
      img5: "https://m.media-amazon.com/images/I/51PDeyFzo1L._SL1500_.jpg",
      price: 2999,
      discount: 7,
      qty: 1,
      category: "earbud",
    },
    {
      id: crypto.randomUUID(),
      title:
        "pTron Bassbuds Duo in Ear Earbuds with 32Hrs Total Playtime, Bluetooth 5.1 Wireless, Stereo Audio, Touch Control TWS, with Mic, Type-C Fast Charging, IPX4 & Voice Assistance (Black)",
      img: "https://m.media-amazon.com/images/I/31G1NouVxaL._SY300_SX300_.jpg",
      img2: "https://m.media-amazon.com/images/I/61Coiv6SLXL._SY450_.jpg",
      img3: "https://m.media-amazon.com/images/I/61jkqxMB4jL._SY450_.jpg",
      img4: "https://m.media-amazon.com/images/I/51+tZ3xiA7L._SL1100_.jpg",
      img5: "https://m.media-amazon.com/images/I/51wi0sZVqyL._SL1100_.jpg",
      price: 2599,
      discount: 71,
      qty: 1,
      category: "earbud",
    },
    {
      id: crypto.randomUUID(),
      title:
        "Boult Audio Z25 True Wireless in Ear Earbuds with 32H Playtime, 45ms Low Latency, Type-C Fast Charging (10=150Mins), Made in India, Zen ENC Mic, 13mm Bass Drivers, Bluetooth 5.3 Ear Buds (Blue Moss)",
      img: "https://m.media-amazon.com/images/I/71vlByXS-JL._SL1500_.jpg",
      img2: "https://m.media-amazon.com/images/I/81KqErUpBOL._SL1500_.jpg",
      img3: "https://m.media-amazon.com/images/I/81v+dv-6KAL._SL1500_.jpg",
      img4: "https://m.media-amazon.com/images/I/71akRKumeCL._SL1500_.jpg",
      img5: "https://m.media-amazon.com/images/I/81T79XX+wUL._SL1500_.jpg",
      price: 2999,
      discount: 63,
      qty: 1,
      category: "earbud",
    },
    {
      id: crypto.randomUUID(),
      title:
        "Boult Audio X30 True Wireless in Ear Earbuds with 40H Playtime, Quad Mic ENC, 45ms Xtreme Low Latency, Made in India, Type-C Fast Charging, 3 Equalizer Modes (Rock, BoomX, Hi-Fi), BT 5.1 (Blue)",
      img: "https://m.media-amazon.com/images/I/71ey9w1JYTL._SL1500_.jpg",
      img2: "https://m.media-amazon.com/images/I/71xO47tyYsL._SL1500_.jpg",
      img3: "https://m.media-amazon.com/images/I/71m50Eny0EL._SL1500_.jpg",
      img4: "https://m.media-amazon.com/images/I/61RgoMA9XDL.SL1500.jpg",
      img5: "	https://m.media-amazon.com/images/I/81OBQ+eI1uL.SL1500.jpg",
      price: 4999,
      discount: 70,
      qty: 1,
      category: "earbud",
    },
    {
      id: crypto.randomUUID(),
      title:
        "boAt Airdopes 121v2 in-Ear True Wireless Earbuds with Upto 14 Hours Playback, 8MM Drivers, Battery Indicators, Lightweight Earbuds & Multifunction Controls (Active Black, with Mic)",
      img: "https://m.media-amazon.com/images/I/61o2urRxrcL.SL1500.jpg",
      img2: "https://m.media-amazon.com/images/I/61o2urRxrcL.SL1500.jpg",
      img3: "https://m.media-amazon.com/images/I/61j3VLyxkHL.SL1500.jpg",
      img4: "https://m.media-amazon.com/images/I/61aBVyNtImL.SL1500.jpg",
      img5: "https://m.media-amazon.com/images/I/71JFUxjducL.SL1500.jpg",
      price: 2990,
      discount: 57,
      qty: 1,
      category: "earbud",
    },
    {
      id: crypto.randomUUID(),
      title:
        "Blaupunkt BTW07 ANC Moksha-30Db Bluetooth Truly Wireless In Ear Earbuds with Mic, Flip Top Rotatory Design, 40H Playtime, TurboVolt Fast Charging, Crispr Enc Tech, GameOn with 80Ms Low Latency (Black)",
      img: "https://m.media-amazon.com/images/I/31XeLoY52sL.SY300_SX300.jpg",
      img2: "https://m.media-amazon.com/images/I/61iJdWkaQ+L.SY450.jpg",
      img3: "https://m.media-amazon.com/images/I/71Tg5d5phGL.SY450.jpg",
      img4: "https://m.media-amazon.com/images/I/61KdB+bNUFL.SY450.jpg",
      img5: "https://m.media-amazon.com/images/I/61lxhBySpLL.SY450.jpg",
      price: 5999,
      discount: 58,
      qty: 1,
      category: "earbud",
    },
    {
      id: crypto.randomUUID(),
      title: `pTron Bassbuds Fute 5.1 Bluetooth Truly Wireless Featherlite TWS in Ear Earbuds with Mic 25Hrs Playtime, 13Mm Dynamic Driver, Immersive Audio, Touch Control, Voice Assistance & Fast Charging (Black)`,
      img: "https://m.media-amazon.com/images/I/51PNGyUNvmL.SL1100.jpg",
      img2: "https://m.media-amazon.com/images/I/61dElFbRplL.SL1100.jpg",
      img3: "https://m.media-amazon.com/images/I/51Im+twUG4L.SL1100.jpg",
      img4: "https://m.media-amazon.com/images/I/61un6wGaIjL.SL1100.jpg",
      img5: "https://m.media-amazon.com/images/I/513-c5luOmL.SL1100.jpg",
      price: 3299,
      discount: 79,
      qty: 1,
      category: "earbud",
    },
    {
      id: crypto.randomUUID(),
      title: `Boult Audio X1 Buds True Wireless in Ear Earbuds with 24H Playtime, Quad Mic ENC, Made in India, Type-C Fast Charging, Environmental Noise Cancellation, 10mm Bass Drivers, TWS Airbass ear buds (Black)`,
      img: "https://m.media-amazon.com/images/I/71mT2gCHH+L.SL1500.jpg",
      img2: "https://m.media-amazon.com/images/I/81Nov7kscML.SL1500.jpg",
      img3: "https://m.media-amazon.com/images/I/91teZ0CgAKL.SL1500.jpg",
      img4: "https://m.media-amazon.com/images/I/71aL6iUS8KL.SL1500.jpg",
      img5: "https://m.media-amazon.com/images/I/71o4W7JuPtL.SL1500.jpg",
      price: 6999,
      discount: 74,
      qty: 1,
      category: "earbud",
    },
    {
      id: crypto.randomUUID(),
      title: `Boult Audio Powerbuds True Wireless in Ear Earbuds with 120H Playtime, in-Built Powerbank, Type-C Fast Charging, Made in India, Pro+ Calling HD Mic, IPX7 Waterproof, Bluetooth Ear Buds TWS (Black)`,
      img: "https://m.media-amazon.com/images/I/71jrExswt4L.SL1500.jpg",
      img2: "https://m.media-amazon.com/images/I/71HAe9bru5L.SL1500.jpg",
      img3: "https://m.media-amazon.com/images/I/71wUXtQVVjL.SL1500.jpg",
      img4: "https://m.media-amazon.com/images/I/81r6fKyraKL.SL1500.jpg",
      img5: "https://m.media-amazon.com/images/I/71-cfdI-CBL.SL1500.jpg",
      price: 8999,
      discount: 83,
      qty: 1,
      category: "earbud",
    },
    {
      id: crypto.randomUUID(),
      title: `Noise Buds Vs104 Bluetooth Truly Wireless in Ear Earbuds with Mic, 30-Hours of Playtime, Instacharge, 13Mm Driver and Hyper Sync (Charcoal Black)`,
      img: "https://m.media-amazon.com/images/I/51cjIEYU8BL.SL1500.jpg",
      img2: "https://m.media-amazon.com/images/I/61gE89QmD+L.SL1500.jpg",
      img3: "https://m.media-amazon.com/images/I/51r57IhfBwL.SL1500.jpg",
      img4: "https://m.media-amazon.com/images/I/513az8Cho7L.SL1500.jpg",
      img5: "https://m.media-amazon.com/images/I/517pNu7bWJL.SL1500.jpg",
      price: 3499,
      discount: 69,
      qty: 1,
      category: "earbud",
    },
  ],
  tshirt: [
    {
      id: crypto.randomUUID(),
      title: `Allen Solly Men's Regular Fit Polo`,
      img: "https://m.media-amazon.com/images/I/71eUwDk8z+L.UY879.jpg",
      img2: "https://m.media-amazon.com/images/I/71mh8ZJZFuL.UX569.jpg",
      img3: "https://m.media-amazon.com/images/I/71vSLpVgZpL.UX569.jpg",
      img4: "https://m.media-amazon.com/images/I/71J8pbcn8WL.UX569.jpg",
      img5: "https://m.media-amazon.com/images/I/71Xu6C8X5sL.UX569.jpg",
      price: 1099,
      discount: 47,
      qty: 1,
      category: "tshirt",
    },
    {
      id: crypto.randomUUID(),
      title: `Veirdo Polo T Shirts for Men, Cotton Polo Neck T Shirts for Men, Half Sleeves Men Polo Tshirt, Classic Polo T Shirts for Men, Men's Regular Polo Shirt`,
      img: "https://m.media-amazon.com/images/I/51lP3VinwoL.UY879.jpg",
      img2: "https://m.media-amazon.com/images/I/313gxA5aDLL.SR38,50.jpg",
      img3: "https://m.media-amazon.com/images/I/51p4Lh0xBBL.UX569.jpg",
      img4: "https://m.media-amazon.com/images/I/61b610JzsZL.UX569.jpg",
      img5: "https://m.media-amazon.com/images/I/512nCuSkPvL.UX679.jpg",
      price: 1199,
      discount: 68,
      qty: 1,
      category: "tshirt",
    },
    {
      id: crypto.randomUUID(),
      title: `AUSK Men's Henley Neck Full Sleeves Regular Fit Cotton T-Shirts`,
      img: "https://m.media-amazon.com/images/I/7152RCSU4LL.UX569.jpg",
      img2: "https://m.media-amazon.com/images/I/61sN03JSBVL.UX569.jpg",
      img3: "https://m.media-amazon.com/images/I/61sJSqUbdIL.UX569.jpg",
      img4: "https://m.media-amazon.com/images/I/61orVltZ7aL.UX569.jpg",
      img5: "https://m.media-amazon.com/images/I/512nCuSkPvL.UX679.jpg",
      price: 1449,
      discount: 76,
      qty: 1,
      category: "tshirt",
    },
    {
      id: crypto.randomUUID(),
      title: `Lyned Mens Cotton Half Sleeve Striped Polo T Shirt with Collar`,
      img: "https://m.media-amazon.com/images/I/71pNnnaOIzS.UY741.jpg",
      img2: "https://m.media-amazon.com/images/I/81qde+GbXzS.UL1500.jpg",
      img3: "https://m.media-amazon.com/images/I/71OQQEULimS.UL1500.jpg",
      img4: "https://m.media-amazon.com/images/I/61OCQ1emmYS.UL1500.jpg",
      img5: "https://m.media-amazon.com/images/I/512nCuSkPvL.UX679.jpg",
      price: 2499,
      discount: 73,
      qty: 1,
      category: "tshirt",
    },
    {
      id: crypto.randomUUID(),
      title: `AELOMART Men's T Shirt-(Amt250105-P_Green)`,
      img: "https://m.media-amazon.com/images/I/71O1QaI-sbL.UY741.jpg",
      img2: "https://m.media-amazon.com/images/I/313hld9yJYL.SR38,50.jpg",
      img3: "https://m.media-amazon.com/images/I/71IS7Oxhv4L.UY550.jpg",
      img4: "https://m.media-amazon.com/images/I/71qJJoWrioL.UY550.jpg",
      img5: "https://m.media-amazon.com/images/I/41TKkmIEiyL.jpg",
      price: 1499,
      discount: 67,
      qty: 1,
      category: "tshirt",
    },
    {
      id: crypto.randomUUID(),
      title: `Campus Sutra Men's Blue and White Ombre Dri-Fit Activewear T-Shirt Regular Fit for Casual Wear | Structured T-Shirt Crafted with Comfort Fit and High-Performance for Everyday Wear`,
      img: "https://m.media-amazon.com/images/I/61MjKYTzgQS.UX679.jpg",
      img2: "https://m.media-amazon.com/images/I/41O5F1Fwa-S.SR38,50.jpg",
      img3: "https://m.media-amazon.com/images/I/71ULOze-C9S.UX679.jpg",
      img4: "https://m.media-amazon.com/images/I/71VawsSnKaL.UX679.jpg",
      img5: "https://m.media-amazon.com/images/I/71ZjxJKa16L.UX679.jpg",
      price: 1449,
      discount: 67,
      qty: 1,
      category: "tshirt",
    },
    {
      id: crypto.randomUUID(),
      title: `EYEBOGLER Men's Striped Regular Fit T-Shirt (T428HS_Blue XL) EYEBOGLERMenRegularT-Shirt`,
      img: "https://m.media-amazon.com/images/I/51zPkF2QEDL.SY741._SX._UX._SY._UY.jpg",
      img2: "https://m.media-amazon.com/images/I/51J3B0pv4YL.UX569.jpg",
      img3: "https://m.media-amazon.com/images/I/51k5XjXCDLL.SY741._SX._UX._SY._UY.jpg",
      img4: "https://m.media-amazon.com/images/I/51mafXDEOoL.SY741._SX._UX._SY._UY.jpg",
      img5: "https://m.media-amazon.com/images/I/81+4kqbFVvL.SX679._SX._UX._SY._UY.jpg",
      price: 1299,
      discount: 69,
      qty: 1,
      category: "tshirt",
    },
    {
      id: crypto.randomUUID(),
      title: `Urbano Fashion Men's Graphic Printed Round Neck Half Sleeve Slim Fit Cotton T-Shirt`,
      img: "https://m.media-amazon.com/images/I/812LCdKokXL.UX679.jpg",
      img2: "https://m.media-amazon.com/images/I/71CfH9fxKYL.UX679.jpg",
      img3: "https://m.media-amazon.com/images/I/41T6QdEsZmL.SR38,50.jpg",
      img4: "https://m.media-amazon.com/images/I/71xLe5pvS5L.UX679.jpg",
      img5: "https://m.media-amazon.com/images/I/81Qp88He8ZL.UX679.jpg",
      price: 999,
      discount: 63,
      qty: 1,
      category: "tshirt",
    },
  ],
  shoes: [
    {
      id: crypto.randomUUID(),
      title: `AVANT Men's Ultra Light Running and Training Shoes`,
      img: "https://m.media-amazon.com/images/I/61rpE6+B6EL.UL1000.jpg",
      img2: "https://m.media-amazon.com/images/I/61ZOVvtxkHL.UL1438.jpg",
      img3: "https://m.media-amazon.com/images/I/61K6TxeJUcL.UL1500.jpg",
      img4: "https://m.media-amazon.com/images/I/61K6TxeJUcL.UL1500.jpg",
      img5: "	https://m.media-amazon.com/images/I/51z-s8y0RWL.UL1500.jpg",
      price: 1599,
      discount: 59,
      qty: 1,
      category: "shoes",
    },
    {
      id: crypto.randomUUID(),
      title: `ASIAN Men's Thar-04 Sports Running,Walking & Gym Shoes with Eva Sole Extra Jump Casual Sneaker Shoes for Men's & Boy's…`,
      img: "https://m.media-amazon.com/images/I/610fN3RyKFL.UL1100.jpg",
      img2: "https://m.media-amazon.com/images/I/717P-nWUGkL.UL1100.jpg",
      img3: "https://m.media-amazon.com/images/I/61Gg25qBH6L.UL1100.jpg",
      img4: "https://m.media-amazon.com/images/I/61VgGxQtSwL.UL1100.jpg",
      img5: "https://m.media-amazon.com/images/I/61kVGCH4bYL.UL1100.jpg",
      price: 649,
      discount: 19,
      qty: 1,
      category: "shoes",
    },
    {
      id: crypto.randomUUID(),
      title: `ASIAN Crystal-13 Sports Running,Walking & Gym Shoes with Crystal Cushion Technology Lightweight Casual Sneaker Shoes for Men's & Boy's`,
      img: "https://m.media-amazon.com/images/I/51rdBvOe1+L.UL1100.jpg",
      img2: "https://m.media-amazon.com/images/I/61-PGOXrVeL.UL1500.jpg",
      img3: "https://m.media-amazon.com/images/I/61BNP0y86fL.UL1500.jpg",
      img4: "https://m.media-amazon.com/images/I/51LZUELy+zL.UL1100.jpg",
      img5: "https://m.media-amazon.com/images/I/61lep9KLIrL.UL1100.jpg",
      price: 2299,
      discount: 45,
      qty: 1,
      category: "shoes",
    },
    {
      id: crypto.randomUUID(),
      title: `ASIAN Men's Wonder-13 Sports Running Shoes`,
      img: "https://m.media-amazon.com/images/I/61utX8kBDlL.UL1100.jpg",
      img2: "https://m.media-amazon.com/images/I/611rLwm1DLL.UL1280.jpg",
      img3: "https://m.media-amazon.com/images/I/61qgw+hqm5L.UL1100.jpg",
      img4: "https://m.media-amazon.com/images/I/61U70iqOAIL.UL1100.jpg",
      img5: "https://m.media-amazon.com/images/I/61yg+IEecXL.UL1100.jpg",
      price: 699,
      discount: 25,
      qty: 1,
      category: "shoes",
    },
    {
      id: crypto.randomUUID(),
      title: `BRUTON Men's Sports Shoes Sports`,
      img: "https://m.media-amazon.com/images/I/71A7mJgXCxL.UL1500.jpg",
      img2: "https://m.media-amazon.com/images/I/71j6TosLiwS.UL1500.jpg",
      img3: "https://m.media-amazon.com/images/I/71iuQCgFToS.UL1500.jpg",
      img4: "https://m.media-amazon.com/images/I/71KXZ0QCypS.UL1500.jpg",
      img5: "https://m.media-amazon.com/images/I/71wg2wFEwjS.UL1500.jpg",
      price: 1299,
      discount: 70,
      qty: 1,
      category: "shoes",
    },
    {
      id: crypto.randomUUID(),
      title: `Campus Men's Hurricane Running Shoes`,
      img: "https://m.media-amazon.com/images/I/61+E6-WZBGL.UL1440.jpg",
      img2: "https://m.media-amazon.com/images/I/61LZrCMUl3L.UL1440.jpg",
      img3: "https://m.media-amazon.com/images/I/71CALuCptDL.UL1440.jpg",
      img4: "https://m.media-amazon.com/images/I/71Spy9mHrIL.UL1500.jpg",
      img5: "https://m.media-amazon.com/images/I/61VutC63EhL.UL1440.jpg",
      price: 1299,
      discount: 46,
      qty: 1,
      category: "shoes",
    },
    {
      id: crypto.randomUUID(),
      title: `AVANT Men's Ultra Light Running and Training Shoes`,
      img: "https://m.media-amazon.com/images/I/61rpE6+B6EL.UL1000.jpg",
      img2: "https://m.media-amazon.com/images/I/61ZOVvtxkHL.UL1438.jpg",
      img3: "https://m.media-amazon.com/images/I/61K6TxeJUcL.UL1500.jpg",
      img4: "https://m.media-amazon.com/images/I/51fOK2ZRVuL.jpg",
      img5: "https://m.media-amazon.com/images/I/51z-s8y0RWL.UL1500.jpg",
      price: 1599,
      discount: 59,
      qty: 1,
      category: "shoes",
    },
    {
      id: crypto.randomUUID(),
      title: `Skechers Mens Glide-Step Sport - New Approa Casual Shoe`,
      img: "https://m.media-amazon.com/images/I/81+AshsrWXL.UL1500.jpg",
      img2: "https://m.media-amazon.com/images/I/51N5bWr2c3L.UL1200.jpg",
      img3: "https://m.media-amazon.com/images/I/51geeHEMtcL.UL1200.jpg",
      img4: "https://m.media-amazon.com/images/I/71x+yichhPL.UL1500.jpg",
      img5: "https://m.media-amazon.com/images/I/71RpRztxpZL.UL1500.jpg",
      price: 7449,
      discount: 54,
      qty: 1,
      category: "shoes",
    },
    {
      id: crypto.randomUUID(),
      title: `Reebok Men's Energy Runner LP Nacho/Conavy/None Running Shoes`,
      img: "https://m.media-amazon.com/images/I/41dXa2CVvPL.jpg",
      img2: "https://m.media-amazon.com/images/I/41dPvRdBOaL.jpg",
      img3: "https://m.media-amazon.com/images/I/61lSwjoTWTL.UL1056.jpg",
      img4: "https://m.media-amazon.com/images/I/61FxEx82uIL.UL1056.jpg",
      img5: "https://m.media-amazon.com/images/I/51cCRUVofKL.UL1056.jpg",
      price: 2499,
      discount: 50,
      qty: 1,
      category: "shoes",
    },
    {
      id: crypto.randomUUID(),
      title: `ASIAN Men's Wonder-13 Sports Running Shoes`,
      img: "https://m.media-amazon.com/images/I/616zTSviLpL.UL1100.jpg",
      img2: "https://m.media-amazon.com/images/I/61XYz5y6RjL.UL1100.jpg",
      img3: "https://m.media-amazon.com/images/I/611uwBsiJeL.UL1100.jpg",
      img4: "https://m.media-amazon.com/images/I/61fcrs07c6L.UL1100.jpg",
      img5: "https://m.media-amazon.com/images/I/61eY3EBVYCL.UL1100.jpg",
      price: 699,
      discount: 25,
      qty: 1,
      category: "shoes",
    },
    {
      id: crypto.randomUUID(),
      title: `Adidas Mens Response Solar Running Shoe`,
      img: "https://m.media-amazon.com/images/I/714a6H-+ygL.UL1500.jpg",
      img2: "https://m.media-amazon.com/images/I/71EFveuVmUL.UL1500.jpg",
      img3: "https://m.media-amazon.com/images/I/71UItRu+HmL.UL1500.jpg",
      img4: "https://m.media-amazon.com/images/I/81YG8m-QY9L.UL1500.jpg",
      img5: "https://m.media-amazon.com/images/I/51rq9AiMkZL.UL1024.jpg",
      price: 7599,
      discount: 46,
      qty: 1,
      category: "shoes",
    },
    {
      id: crypto.randomUUID(),
      title: `Adidas Mens Streetgaze M Running Shoes`,
      img: "https://m.media-amazon.com/images/I/71XSP9IVf5L.UL1500.jpg",
      img2: "https://m.media-amazon.com/images/I/81kId-WJOGL.UL1500.jpg",
      img3: "https://m.media-amazon.com/images/I/81vKSHFwhmL.UL1500.jpg",
      img4: "https://m.media-amazon.com/images/I/71Ln33pOhjL.UL1500.jpg",
      img5: "https://m.media-amazon.com/images/I/71XSP9IVf5L.UL1500.jpg",
      price: 4799,
      discount: 50,
      qty: 1,
      category: "shoes",
    },
  ],
  tshirtWomen: [
    {
      id: crypto.randomUUID(),
      title: `FLEXIMAA Women's Cotton Plain V Neck Half Sleeve T-Shirt`,
      img: "https://m.media-amazon.com/images/I/61x8EYIm8hL.UL1500.jpg",
      img2: "https://m.media-amazon.com/images/I/61E+qBY6ZmL.UL1500.jpg",
      img3: "https://m.media-amazon.com/images/I/615NTaN+8QL.UL1500.jpg",
      img4: "https://m.media-amazon.com/images/I/51wIOzCS8QL.UL1500.jpg",
      img5: "https://m.media-amazon.com/images/I/71Wd3GJZzVL.UL1500.jpg",
      price: 699,
      discount: 55,
      qty: 1,
      category: "tshirtwomen",
    },
    {
      id: crypto.randomUUID(),
      title: `TRUEREVO Round Neck Half Sleeve Dry Fit Yoga Workout T Shirt for Women`,
      img: "https://m.media-amazon.com/images/I/71BLosl4pDL.UL1400.jpg",
      img2: "https://m.media-amazon.com/images/I/71vdvB4u97L.UL1400.jpg",
      img3: "https://m.media-amazon.com/images/I/71w+zfeypmL.UL1400.jpg",
      img4: "https://m.media-amazon.com/images/I/71YQoqokl1L.UL1400.jpg",
      img5: "https://m.media-amazon.com/images/I/61GaR57NOFL.UL1400.jpg",
      price: 899,
      discount: 17,
      qty: 1,
      category: "tshirtwomen",
    },
    {
      id: crypto.randomUUID(),
      title: `LEOTUDE Cotton Blend Half Sleeve Oversized T-Shirts for Women's`,
      img: "https://m.media-amazon.com/images/I/61iKv6-unXL.UL1500.jpg",
      img2: "https://m.media-amazon.com/images/I/61Fuee5PwiL.UL1500.jpg",
      img3: "https://m.media-amazon.com/images/I/61cvw4chTtL.UL1500.jpg",
      img4: "https://m.media-amazon.com/images/I/61bzvKukDhL.SX425._SX._UX._SY._UY.jpg",
      img5: "https://m.media-amazon.com/images/I/61571C4Q3tL.SY550._SX._UX._SY._UY.jpg",
      price: 1099,
      discount: 73,
      qty: 1,
      category: "tshirtwomen",
    },
    {
      id: crypto.randomUUID(),
      title: `LEOTUDE Cotton Blend Half Sleeve Oversized Back Printed Women's T-Shirt`,
      img: "https://m.media-amazon.com/images/I/71P5TSBvg9L.UL1500.jpg",
      img2: "https://m.media-amazon.com/images/I/61j4tdciTqL.UL1500.jpg",
      img3: "https://m.media-amazon.com/images/I/61z5DyZT31L.UL1500.jpg",
      img4: "https://m.media-amazon.com/images/I/61cvw4chTtL.UL1500.jpg",
      img5: "https://m.media-amazon.com/images/I/71P5TSBvg9L.UL1500.jpg",
      price: 1099,
      discount: 67,
      qty: 1,
      category: "tshirtwomen",
    },
  ],
};

export default product2;
